services:
  db:
    image: docker.io/postgres:latest
    container_name: project-draft-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-draft-app
    command: cargo watch -x run
    volumes:
      - .:/app:Z
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - APP_APPLICATION__HOST=0.0.0.0
      - APP_DATABASE__HOST=db
      - APP_DATABASE__PORT=5432
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    restart: unless-stopped

volumes:
  postgres_data:
